### ISSUE TITLE
Feedback of Milestone 1

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/PyDataPeek#16]
- Functions in this package: Explain more detailed thing of what the function does, and what is input, etc (At least two sentence)
- Project Proposal: Subjective tone, avoid using ‘we’. (Remember, this is package instructions for user, not TA). 
- Team member’s name used be in Contributor file.
- Please close the finished issue, helps TA and teammate to track.

**Comment by Doooooris** [comment]
- Add dependency too

**Comment by MrThomasPin** [comment]
- [x] Functions in this package: Explain more detailed thing of what the function does, and what is input, etc (At least two sentence)
- [x] Project Proposal: Subjective tone, avoid using ‘we’. (Remember, this is package instructions for user, not TA). 
- [x] Team member’s name used be in Contributor file.
- [x] Please close the finished issue, helps TA and teammate to track.
